#!/bin/sh

revert() {
  xset dpms 300 300 300
}
trap revert HUP INT TERM
xset dpms 5 5 5
xset dpms force off

# We cannot use gnome-screensaver-command because we
# need the nofork option.
i3lock -n -c 000000

revert
